name: "Build/Tests"
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: go build ./...
      - name: Unit tests
        run: go test -race -v ./...

